### ISSUE TITLE
2021.3.23f1 Editor Error with Profiler Window

### ISSUE THREAD

**Issue by SanghunK** [lukakldiashvili/Unified-Universal-Blur#1]
Hi,
First of all, thank you for sharing good source. I'm really making good use of this.
But, I found a bug with unity version 2021.3.23f1.
If you open the Profiler window and press the Play button in editor, you can see a lot of error message in Console window.

this error: Missing Profiler.EndSample (Every BeginSample call must have a subsequent EndSample call within the same frame): FullScreenPassRendererFeature
![image](https://user-images.githubusercontent.com/18112611/236974717-6cfb28be-109b-4bcd-9b92-efb6613ad04e.png)

I think it's bug on Unity side. Because it works well with 2022 version.
But I wanted to let you know, and if you can fix it, please fix it.

Thank you.

**Comment by lukakldiashvili** [comment]
Thank you for reaching out.

I have released a new version, please take a look and feel free to share any feedback!

**Comment by SanghunK** [comment]
Wow! The new version is works well. I really appreciate it!
