### ISSUE TITLE
Heap allocations resulting in significant preformance loss.

### ISSUE THREAD

**Issue by matyX6** [lukakldiashvili/Unified-Universal-Blur#10]
I loved this blur effect for URP but to an unpleasant surprise I find the asset has heap allocation resulting in performance loss... This is how I fixed the problem by cacheing "PassData" object to not be created and garbage collected every pass. Images attached here:

![gc_1](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/38249194/07262dab-b620-403c-8ec2-bef94b44ebd4)
![gc_2](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/38249194/ea77adc4-7500-4a92-8d4a-b3b0c2072ff0)

**Comment by lukakldiashvili** [comment]
Thank you for bringing up the issue. Will take a look when possible and release an updated version.

**Comment by lukakldiashvili** [comment]
Fixed this issue in the latest release [0.2.3](https://github.com/lukakldiashvili/Unified-Universal-Blur/releases/tag/0.2.3)

Feel free to re-evaluate the performance and please, share the results if you find something of interest.
Again, thank you.

**Comment by matyX6** [comment]
Issue is fixed and performance is back to normal. Thank you for the fast update!
