### ISSUE TITLE
stop error

### ISSUE THREAD

**Issue by xiezi5160** [lukakldiashvili/Unified-Universal-Blur#11]
MissingReferenceException: The object of type 'RenderTexture' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Unified.Universal.Blur.UniversalBlurPass.Dispose () (at Assets/UnifiedUniversalBlur/Scripts/UniversalBlurPass.cs:44)
Unified.Universal.Blur.UniversalBlurFeature.Dispose (System.Boolean disposing) (at Assets/UnifiedUniversalBlur/Scripts/UniversalBlurFeature.cs:81)

**Comment by lukakldiashvili** [comment]
Fixed in [0.2.4](https://github.com/lukakldiashvili/Unified-Universal-Blur/releases/tag/0.2.4)

**Comment by xiezi5160** [comment]
> Fixed in [0.2.4](https://github.com/lukakldiashvili/Unified-Universal-Blur/releases/tag/0.2.4)

Thx~
