### ISSUE TITLE
Assembly Definition Files must match

### ISSUE THREAD

**Issue by AldeRoberge** [lukakldiashvili/Unified-Universal-Blur#18]
![image](https://github.com/lukakldiashvili/Unified-Universal-Blur/assets/4276275/0a08be9c-6c0e-42d3-8d97-d26005f22e05)
(missing dot)

Not a big deal, but as a big fan of this asset I wanted to let you know there's a very small typo in the name of the .asmdef files, as shown in the picture.

Thanks for the earlier fix, this has fixed the build problem I was having.

**Comment by lukakldiashvili** [comment]
Thank you for raising the issue and the earlier one as well!
If you have more feedback, please let me know.

Fix: [commit](https://github.com/lukakldiashvili/Unified-Universal-Blur/commit/65ea8c1c69f215058e9ccef0d492971510a67154)
