### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by guinhx** [lukakldiashvili/Unified-Universal-Blur#9]
I'm having memory leak problems when activating the feature in the URP settings. After some time playing the memory usage just goes up until it reaches a point where it uses more than 5gb of ram. Without the Blur feature active in the URP features this does not occur.

**Comment by lukakldiashvili** [comment]
What version of the Unity are you encountering the problem with?

**Comment by guinhx** [comment]
Unity Version: 2022.3.9f1

**Comment by BoysheO** [comment]
URP has a terrible bug in past.It's about RendererTexture leak?It's a unity bug.

**Comment by jedjoud10** [comment]
Still happening on 202.3.16f1. Had to disable the renderer feature to stop unity from crashing.

**Comment by lukakldiashvili** [comment]
> Still happening on 202.3.16f1. Had to disable the renderer feature to stop unity from crashing.

Will look into it.

**Comment by lukakldiashvili** [comment]
I have released a fix for this issue in [Version 0.3.1](https://github.com/lukakldiashvili/Unified-Universal-Blur/releases/tag/0.3.1)

Looking forward to hearing your feedback!
